### ISSUE TITLE
Compilation Error in app/persona/controllers/Offers.scala

### ISSUE THREAD

**Issue by d77kim** [TeamPersona/Persona-API#3]
Error:(23, 34) object routes is not a member of package persona.controllers
    Redirect(persona.controllers.routes.Offers.get(id))

**Comment by taylorstark** [comment]
Works for me.  Make sure in your IntelliJ run configuration that you remove "Make" from "before launch"

**Comment by rpcrezel** [comment]
Did that, still does not compile for me either

**Comment by taylorstark** [comment]
Try compiling from a command line:
brew install sbt
sbt run

**Comment by d77kim** [comment]
Yes, it runs. But there is a compilation error. Are we just going to ignore it?

**Comment by taylorstark** [comment]
How can it run if there is a compilation error? That's contradictory

**Comment by d77kim** [comment]
Okay. Why is make removed though?

**Comment by taylorstark** [comment]
Make uses IntelliJ's scala compiler, which doesn't know how to compile the "routes" file (since it's not a scala file).  That's why IntelliJ reports an error, even though there isn't one
